name: Build and Run

on: [push, pull_request]

env:
  PY_MODULE_ENTRY_SCRIPT: "habiter"

jobs:
  build_and_run:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        py-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py-version }}
      - name: Ensure pip is up-to-date
        shell: bash
        run: |
          python -m pip install --upgrade pip

      # All project dependencies are installed during this step
      - name: Build and Run
        shell: bash
        run: |
          pip install -e .
          ${{ env.PY_MODULE_ENTRY_SCRIPT }} --version
