name: Lint, Run, and Test

on: [push, pull_request]

jobs:
  lint_run_test:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      - name: Lint with flake8
        run: flake8 . --count --show-source --statistics

      - name: Run
        run: |
          pip install -e .
          habiter add test

      - name: Test
        run: pytest -v
